"""MongoDB document models using Pydantic."""

from datetime import datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, Field


def generate_id() -> str:
    """Generate a unique ID."""
    return str(uuid4())


class Trade(BaseModel):
    """Record of executed trades."""

    id: str = Field(default_factory=generate_id, alias="_id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    platform: Literal["kalshi", "polymarket"]
    market_id: str
    market_title: str | None = None

    side: Literal["buy", "sell"]
    price: Decimal  # In cents (0-100)
    size: Decimal  # Number of contracts
    fees: Decimal | None = None

    status: Literal["pending", "filled", "cancelled", "rejected"]
    filled_at: datetime | None = None

    signal_source: Literal["copy", "ai", "arb"] | None = None
    signal_id: str | None = None

    pnl: Decimal | None = None
    notes: dict[str, Any] | None = None

    class Config:
        populate_by_name = True


class Position(BaseModel):
    """Current open positions."""

    id: str = Field(default_factory=generate_id, alias="_id")

    platform: Literal["kalshi", "polymarket"]
    market_id: str
    market_title: str | None = None

    side: Literal["yes", "no"]
    size: Decimal
    avg_entry_price: Decimal

    current_value: Decimal | None = None
    unrealized_pnl: Decimal | None = None

    opened_at: datetime = Field(default_factory=datetime.utcnow)
    last_updated: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True


class Signal(BaseModel):
    """Trading signals generated by agents."""

    id: str = Field(default_factory=generate_id, alias="_id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    source: Literal["copy_monitor", "ai_analyst", "arb_detector"]
    platform: Literal["kalshi", "polymarket"]
    market_id: str

    action: Literal["buy", "sell", "hold"]
    confidence: Decimal | None = None  # 0.0 to 1.0
    reasoning: str | None = None

    metadata: dict[str, Any] | None = None
    acted_on: bool = False
    trade_id: str | None = None

    class Config:
        populate_by_name = True


class MetricsDaily(BaseModel):
    """Daily performance metrics."""

    id: str = Field(default_factory=generate_id, alias="_id")
    date: datetime  # Date for these metrics

    starting_value: Decimal
    ending_value: Decimal
    pnl: Decimal

    trades_count: int
    win_count: int = 0
    loss_count: int = 0
    win_rate: Decimal | None = None  # 0.0 to 1.0

    sharpe_ratio: Decimal | None = None
    max_drawdown: Decimal | None = None

    ai_cost: Decimal | None = None
    fees_paid: Decimal | None = None

    class Config:
        populate_by_name = True


class Alert(BaseModel):
    """System alerts."""

    id: str = Field(default_factory=generate_id, alias="_id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    level: Literal["info", "warning", "critical"]
    alert_type: str
    message: str

    acknowledged: bool = False
    acknowledged_at: datetime | None = None
    acknowledged_by: str | None = None

    class Config:
        populate_by_name = True


class TrackedTrader(BaseModel):
    """A trader being monitored for copy trading."""

    id: str = Field(default_factory=generate_id, alias="_id")
    address: str
    platform: Literal["kalshi", "polymarket"]

    win_rate: Decimal | None = None
    pnl_30d: Decimal | None = None
    avg_position_size: Decimal | None = None

    last_trade_at: datetime | None = None
    active: bool = True
    added_at: datetime = Field(default_factory=datetime.utcnow)

    notes: str | None = None

    class Config:
        populate_by_name = True
